Adjust tests and integrate yaci-devkit in CI

diff --git a/.github/workflows/intergration-test.yml b/.github/workflows/intergration-test.yml
--- a/.github/workflows/intergration-test.yml
+++ b/.github/workflows/intergration-test.yml
@@ -9,6 +9,7 @@ on:
     branches:
       - main
       - develop
+  workflow_dispatch:
 
 jobs:
   commit-build:
@@ -19,9 +20,32 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           submodules: 'true'
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20.8.0'
+
+      - name: Install Yaci DevKit
+        run: npm install -g @bloxbean/yaci-devkit
+
+      - name: Start Yaci DevKit in background
+        run: nohup  yaci-devkit up --enable-yaci-store &
+
+      - name: Wait for Yaci DevKit to start
+        run: |
+          for i in {1..30}; do
+            if nc -z localhost 8080; then
+              echo "Yaci DevKit is up!"
+              exit 0
+            fi
+            echo "Waiting for Yaci DevKit to start..."
+            sleep 5
+          done
+          echo "Yaci DevKit failed to start" >&2
+          exit 1
       - name: Set up JDK 11
         uses: actions/setup-java@v4
         with:
